---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-radarr-movies
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-radarr-movies
  storageClassName: nfs-csi
