---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-radarr-movies
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=3
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: kstorage1/mnt/ssd/movies
    volumeAttributes:
      server: kstorage1
      share: /mnt/ssd/movies
